CFLAGS = -std=gnu11 -Wall -Wextra -lm -fopenmp

.PHONY: all
all: ex2_original ex2_optimised

.PHONY: clean
clean:
	$(RM) ex2_original ex2_optimised

ex2_original: ex2_original.c

ex2_optimised: ex2_optimised.c
